apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spring-app
  name: spring-pod
spec:
  containers:
    - name:  spring-app-container
      image: zaienbdr/spring-app-container:v1
      ports:
        - containerPort: 8080
      env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/springdb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          # to reference a Secret, ConfigMap
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
   